### ISSUE TITLE
项目进度

### ISSUE THREAD

**Issue by yanglbme** [yanglbme/qa#3]
目前项目还差`TimeLine`以及`全文搜索`两大功能没有实现:)，加油干~

**Comment by Sod-Momas** [comment]
加油！୧(๑•̀⌄•́๑)૭------------------ 原始邮件 ------------------发件人: Yang Libin  <notifications@github.com>发送时间: 2018年6月2日 08:30收件人: yanglbme/qa <qa@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[yanglbme/qa] 项目进度 (#3)目前项目还差TimeLine以及全文搜索两大功能没有实现:)，加油干~

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/yanglbme/qa/issues/3","url":"https://github.com/yanglbme/qa/issues/3","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yanglbme/qa","title":"yanglbme/qa","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/yanglbme/qa"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"项目进度 (#3)"}],"action":{"name":"View Issue","url":"https://github.com/yanglbme/qa/issues/3"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "项目进度 (#3)",
"sections": [
{
"text": "",
"activityTitle": "**Yang Libin**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@yanglbme",
"facts": [
{
"name": "Repository: ",
"value": "yanglbme/qa"
},
{
"name": "Issue #: ",
"value": 3
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"yanglbme/qa\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"yanglbme/qa\",\n\"issueId\": 3\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/yanglbme/qa/issues/3"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341696559\n}"
}
],
"themeColor": "26292E"
}
